version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: myImageUser
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    networks:
      - network

  security:
    build: 
      dockerfile: ./jars/DockerfileSecurity
    ports:
      - 9090:9090
    depends_on:
      - db
    networks:
      - network

  client:
    build:
      dockerfile: ./jars/DockerfileClient
    ports:
      - 8080:8080
    networks:
      - network  

  service:
    build:
      dockerfile: GoService/Dockerfile
    ports:
      - 9091:9091
    networks:
      - network

  mongo:
    image: mongo:latest
    ports:
      - "27016:27017"
    networks:
      - network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80
    networks:
      - network

  chart:
    build:
      dockerfile: ./myproject/myproject/Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - network

networks:
    network:
        driver: bridge